univeral_config: &univeral_config
  mode: "pred"
  token_dict_path: tokens/tokens_1024.pt
  num_tokens: 1024
  interval: 5
  num_historical_steps: 20
  num_future_steps: 80

dataset:
  <<: *univeral_config
  root: /mnt/nuplan
  save_dir: /root/wangjunyi/data/planr1
  dir: train

dataloader:
  batch_size: 8
  num_workers: 8
  pin_memory: True
  persistent_workers: True

trainer:
  ckpt_path: ckpts/pre-training.ckpt
  accelerator: "gpu"
  devices: 1
  csv_logger:
    save_dir: lightning_logs
    name: val_pred
  tensorboard_logger:
    save_dir: lightning_logs
    name: val_pred

model:
  <<: *univeral_config
  hidden_dim: 128
  num_heads: 8
  num_attn_layers: 6
  num_hops: 4
  agent_radius: 60
  polygon_radius: 30
  pred_top_k: 1
  val_visualization: False
  val_visualization_interval: 5